version: "3.8"

services:
  fastapi:
    build:
      context: ./fastapi_app
    container_name: api-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./shared_models:/app/shared_models
    depends_on:
      - airflow

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.1
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
#    environment:
#      - MLFLOW_TRACKING_DIR=/mlflow
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --artifacts-destination file:///mlflow/artifacts
      --serve-artifacts
      --host 0.0.0.0

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - fastapi

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build:
      context: ./airflow
    container_name: airflow
    command: bash -c "airflow scheduler & airflow webserver"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: Zbsr_kT5eo9rxkKfFxcJ-nlz2JpqD0CJ27wRxpKZiYw=
      AIRFLOW__WEBSERVER__SECRET_KEY: supersecretkeyexample123
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      PREDICT_API_URL: http://fastapi:8000
      MLFLOW_TRACKING_URI: http://mlflow:5000
      INFERENCE_EXPERIMENT: inference_logs
      INFERENCE_STORE_DIR: /opt/airflow/inference_store
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mlflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./inference_store:/opt/airflow/inference_store

volumes:
  postgres_data:
  airflow_dags:
  airflow_logs:
  airflow_plugins:
  inference_store: 